# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-27 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taco_montes_app', '0002_user_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='resume',
        ),
        migrations.AddField(
            model_name='user',
            name='document',
            field=models.FileField(null=True, upload_to='resume/'),
        ),
    ]
